version: '3.8'

x-common-args: &common-args
    context: ./docker/elasticsearch

x-memlock: &default-memlock
    memlock:
        soft: -1
        hard: -1

services:
    web:
        build:
            context: ./docker/nginx
        container_name: web
        environment:
            - TZ=Asia/Jakarta
        volumes:
            - ./docker/nginx/nginx.conf/:/etc/nginx.conf
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports: 
            - 80:80
        networks:
            - elastic
        links:
            - es01
            - es02
            - es03
            - kib01
        depends_on:
            - es01
            - es02
            - es03
            - kib01
    es01:
        build:
            <<: *common-args
        container_name: es01
        environment:
            - node.name=es01
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es02,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            <<: *default-memlock
        volumes:
            - data01:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - elastic
    es02:
        build:
            <<: *common-args
        container_name: es02
        environment:
            - node.name=es02
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es03
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            <<: *default-memlock
        volumes:
            - data02:/usr/share/elasticsearch/data
        networks:
            - elastic
    es03:
        build:
            <<: *common-args
        container_name: es03
        environment:
            - node.name=es03
            - cluster.name=es-docker-cluster
            - discovery.seed_hosts=es01,es02
            - cluster.initial_master_nodes=es01,es02,es03
            - bootstrap.memory_lock=true
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits: 
            <<: *default-memlock
        volumes:
            - data03:/usr/share/elasticsearch/data
        networks:
            - elastic
    kib01:
        build:
            context: ./docker/kibana
        container_name: kib01
        volumes:
            - type: bind
              source: ./docker/kibana/kibana.yml
              target: /usr/share/kibana/config/kibana.yml
              read_only: true
        environment:
            ELASTICSEARCH_URL: http://es01:9200
            ELASTICSEARCH_HOSTS: '["http://es01:9200","http://es02:9200","http://es03:9200"]'
        ports:
            - 5601:5601
        networks:
            - elastic
volumes:
    data01:
        driver: local
    data02:
        driver: local
    data03:
        driver: local

networks:
    elastic:
        driver: bridge